### ISSUE TITLE
For @dotnetshadow

### ISSUE THREAD

**Issue by tuespetre** [tuespetre/dnx-watch-iis#1]
For @dotnetshadow:

Log Name: Application
Source: HttpPlatformHandler
Date: 20/11/2015 11:58:32 AM
Event ID: 1001
Task Category: None
Level: Information
Keywords: Classic
User: N/A
Computer: DINO
Description:
The description for Event ID 1001 from source HttpPlatformHandler cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event:

Process '9328' started successfully and is listening on port '10147'.

Event Xml:

1001
4
0
0x80000000000000

4656
Application
DINO

Process '9328' started successfully and is listening on port '10147'.

Although it does work with IIS Express, I have tried reinstall the http platform handler many times just don't understand what I'm doing wrong

**Comment by tuespetre** [comment]
@dotnetshadow,

Please provide the following information to help diagnose the issue:
- stop IIS
- delete all logs in the wwwroot/log folder
- make sure stdOutEnabled is true in the web.config and the log path is set to ./log/iis
- clear your application event log
- start IIS and the app pool if necessary 
- make a request to your app
- upload an export of your application event log 
- upload whatever gets written to the log folder

**Comment by tuespetre** [comment]
it seems as though the application is at least starting to run; something must not be right with the web.config or the log folder permissions for you to not get a stdout log, though. You would also see an error about it in the event viewer; for that reason I suspect your stdOutLogEnabled is not set.

**Comment by dotnetshadow** [comment]
I'm happy for you to remote into my machine to have a look if that is easier for you?

**Comment by dotnetshadow** [comment]
Actually I think I just got it working but I don't know how I think I had logs/iis as opposed to ./logs/iis, your screenshot has log/iis

**Comment by dotnetshadow** [comment]
I don't think that's the reason, I think I typed the commands wrong, it would be great if you added maybe text for the various DNX variables so easier to cut and paste I think I may of missed -

**Comment by dotnetshadow** [comment]
Yes I can confirm now that everything is working, thank you so much for this exactly what I've been after for a while I'll update stackoverflow and the other thread

**Comment by dotnetshadow** [comment]
How did u know to pipe the commands together like --dnx-args? where did you find that because when I run dnx --help I don't see that argument?

**Comment by tuespetre** [comment]
That is a dnx-watch thing..

**Comment by dotnetshadow** [comment]
Ahh yes I just saw the documentation on dnx-watch excellent thank you. You don't know how much time you have saved me. Just one very last question the .. in between arguments is that some sort concatenation how did you know how to do that?

**Comment by tuespetre** [comment]
".." Is the next directory up, so "--project .." Tells dnx to run on the next directory up from the wwwroot folder. It has to be specified twice like that so dnx-watch will also get that location.

**Comment by dotnetshadow** [comment]
Sorry to bother you one more time but how would debug the app? Would you have to create a new config in the properties of the solution? IIS Express, EF, Watch, web are currently available  so how would you debug against say site http://local-foo.com

**Comment by tuespetre** [comment]
Debug > Attach to Process, show all user processes, and attach to the appropriate dnx.exe that is running. 

This is kind of tedious until the team(s) come together to make a more slick/integrated solution (I'm sure they will for RTM.) 

There is an extension for Visual Studio from Microsoft to automatically attach to new child processes as they spawn, which would work great for this, but here is an issue I have open (the team is working on it right now): https://github.com/aspnet/IISIntegration/issues/34

**Comment by dotnetshadow** [comment]
Thank you once again, I was actually attaching to dnx but I had to select show all user processors I was attaching to the wrong one

**Comment by dotnetshadow** [comment]
I discovered another issue, I'm not sure if you have tried the authentication stuff in asp.net 5 but I tried authenticating with Facebook everything seems to function I get prompted in Facebook I click accept. In my facebook I have set the website to http://local-foo.com. But ExternalLoginCallback causes an error "An error occurred while processing your request". But I run the same sample using IIS express and change to http://localhost:2421 etc it works fine

This line fails in Account Controller:

```
Line 167: var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false);
```

It doesn't give a descriptive error:

```
? ex.Message
"One or more errors occurred."

Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233088
    HelpLink: null
    InnerException: Count = 1
    InnerExceptions: Count = 1
    Message: "One or more errors occurred."
    Source: "mscorlib"
    StackTrace: "   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNet.Identity.EntityFramework.UserStore`4.<FindByLoginAsync>d__53.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNet.Identity.SignInManager`1.<ExternalLoginSignInAsync>d__37.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at WebApplicationIIS.Cont
rollers.AccountController.<ExternalLoginCallback>d__12.MoveNext() in D:\\Programming\\Projects\\WebApplicationIIS\\src\\WebApplicationIIS\\Controllers\\AccountController.cs:line 167"
    TargetSite: {Void ThrowForNonSuccess(System.Threading.Tasks.Task)}
```

**Comment by tuespetre** [comment]
That sounds more like configuration related stuff having to do with switching from the one URL to the other. I would just check twice and three times about all of the configuration for Facebook OAuth in your app and on Facebook.

**Comment by tuespetre** [comment]
Ah; didn't see you posted a stack trace while I was typing that on my phone. Your stack trace shows you that the problem is coming from EntityFramework somehow. Maybe your application is unable to connect to your database for whatever reason; especially if you used integrated security to connect to SQL Server, for instance.

**Comment by dotnetshadow** [comment]
Ahh ok thanks for pointing me in the right direction, maybe it gives me a better hint, it's just using the localdb thing so not sure if I have to change permissions?

**Comment by dotnetshadow** [comment]
Thanks for your help I managed to get it working using SQL Server instance instead of the localdb, definitely a permissions problem with localdb. I just don't know how to grant the iis appool permissions to a localdb

**Edit:** FYI Fixed the issue following these articles:

http://blogs.msdn.com/b/sqlexpress/archive/2011/12/09/using-localdb-with-full-iis-part-1-user-profile.aspx

http://blogs.msdn.com/b/sqlexpress/archive/2011/12/09/using-localdb-with-full-iis-part-2-instance-ownership.aspx

**Comment by dotnetshadow** [comment]
Would environment variable need to be passed in somehow? For example Development vs Production?
